config/routes.rb
Rails.application.routes.draw do
  resources :lists, only: [:new, :create, :index, :show] do
    resources :bookmarks, only: [:new, :create, :index, :show, :destroy ]
  end
  resources :bookmarks, only: [:destroy ]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list
  validates :movie_id, presence: true
  validates :list_id, presence: true
  validates :movie_id, uniqueness: { scope: :list_id }
  validates :comment, length: { minimum: 6 }



end

## A bookmark must be linked to a movie and a list, and the [movie, list] pairings should be unique.
## The comment of a bookmark cannot be shorter than 6 characters.

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks
  validates :name, presence: true
  validates :name, uniqueness: true


end

## TO DO
## When you delete a list, you should delete all associated bookmarks (but not the movies as they can be referenced in other lists).

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  validates :title, uniqueness: true
  validates :title, presence: true
  validates :overview, presence: true
  # validates uniqueness
  # overview presence true
end

## TO DO
## You can’t delete a movie if it is referenced in at least one bookmark.

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def index
    @bookmarks = Bookmark.all
  end

  def new
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new
  end

  def create
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new(bookmarks_params)
    @bookmark.list = @list
      if @bookmark.save
        redirect_to @list
      else render :new, status: :unprocessable_entity
      end
    end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to lists_path
  end

  private

  def bookmarks_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController


  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
    # @restaurant = Restaurant.find(params[:id])
    # @review = Review.new
  end

  def new
    @list = List.new
    # @restaurant = Restaurant.new
  end

  def create
    @list = List.new(list_params)
      if @list.save
        redirect_to @list
      else render :new, status: :unprocessable_entity
      end
  end

    # @restaurant = Restaurant.new(restaurant_params)
    # if @restaurant.save
    #   redirect_to @restaurant
    # else
    #   render :new, status: :unprocessable_entity
    # end


# def edit
#   # @restaurant = Restaurant.find(params[:id])
# end

# def update
#   # @restaurant = Restaurant.find(params[:id])
#   # @restaurant.update(restaurant_params)
#   # redirect_to restaurant_path(@restaurant)
# end

# def destroy
# #   @restaurant = Restaurant.find(params[:id])
# #   @restaurant.destroy
# #   redirect_to restaurants_path
# # end

private

  def list_params
    params.require(:list).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/index.html.erb
<h1>viewzinha</h1>

<% @bookmarks.each do |b| %>
   <h2>  <%=  "#{b.comment}" %> </h2>
  <% end %>

app/views/bookmarks/new.html.erb
<h1><%= @list.name %></h1>

  <%= simple_form_for [@list, @bookmark] do |f| %>
    <%= f.input :comment %>
    <%= f.association :movie%>
    <%= f.submit %>
  <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<h1>viewzinha</h1>

<% @lists.each do |l| %>
  <h2>  <%= link_to l.name, list_path(l) %> </h2>

  <% end %>

<%= link_to "New list", new_list_path %>
<%= link_to "New bookmark", new_bookmark_path %>

app/views/lists/new.html.erb
<%= @list.name %>

  <%= simple_form_for @list do |f| %>
    <%= f.input :name %>
    <%= f.submit %>
  <% end %>

app/views/lists/show.html.erb
<%= @list.name %>
<%= @bookmarks.each do |b| %>
<h1><%= b.movie.name %></h1>
<h2><%= b.movie.comment %></h2>


<%= link_to "New bookmark", new_list_bookmark_path(@list) %>